name: Output information
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  yaml:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: 'Yamllint'
      uses: karancode/yamllint-github-action@master
      with:
        yamllint_file_or_dir: '.'
        yamllint_config_filepath: .github/workflows/.yamllint
        yamllint_comment: true
